config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pages#home'
  get 'pages/home', to: 'pages#home'

  # get 'recipes', to: 'recipes#index'
  # get 'recipes/new', to: 'recipes#new', as: 'new_recipe'
  # get 'recipes/:id', to: 'recipes#show', as: 'recipe'
  # post 'recipes', to: 'recipes#create'

  resources :recipes

  get 'signup', to: 'chefs#new'
  resources :chefs, except: [:new]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chef.rb
class Chef < ApplicationRecord

  before_save { self.email = email.downcase }

  validates :chefname, presence: true, length: { maximum: 30 }

  VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

  has_many :recipes

  has_secure_password

  validates :password, presence: true, length: { minimum: 5 }, allow_nil: true

end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true, length: { minimum: 5, maximum: 1000 }
  validates :chef_id, presence: true
  belongs_to :chef
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController

  def new
    @chef = Chef.new
  end

  def create
    @chef = Chef.new(chef_params)
    if @chef.save
      flash[:success] = "Welcome #{@chef.chefname}! Start sharing your recipe now."
      redirect_to @chef
    else
      render 'new'
    end
  end

  def show
    @chef = Chef.find(params[:id])
  end

  def edit
    @chef = Chef.find(params[:id])
  end

  def update
    @chef = Chef.find(params[:id])
    if @chef.update(chef_params)
      flash[:success] = "Your account information has been updated!"
      redirect_to @chef
    else
      render 'edit'
    end
  end


  private
  def chef_params
    params.require(:chef).permit(:chefname, :email, :password, :password_confirmation)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home

  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  before_action :set_recipe, only: [:show, :edit, :update]

  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.chef = Chef.first
    if @recipe.save
      flash[:success] = "Your recipe has been created successfully!"
      redirect_to recipe_path(@recipe)
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @recipe.update(recipe_params)
      flash[:success] = "Your recipe has been updated successfully!"
      redirect_to recipe_path(@recipe)
    else
      render 'edit'
    end
  end

  def destroy
    Recipe.find(params[:id]).destroy
    flash[:success] = "Recipe deleted successfully!"
    redirect_to recipes_path
  end

  private
  def recipe_params
    params.require(:recipe).permit(:name, :description)
  end

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.chefname, class: "img-circle")
  end
end

app/views/chefs/_form.html.erb
  <%= render 'shared/error-msg', obj: @chef %>

  <div class="row">
    <div class="col-md-12">
      <%= form_for(@chef, :html => {class: "form-horizontal", role: "form"}) do |f| %>
        <div class="form-group">
          <div class="col-md-2 control-label">
            <%= f.label :chefname, "Choose chefname" %>
          </div>
          <div class="col-md-8">
            <%= f.text_field :chefname, class: "form-control", placeholder: "Enter your name", autofocus: true %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-md-2 control-label">
            <%= f.label :email %>
          </div>
          <div class="col-md-8">
            <%= f.email_field :email, class: "form-control", placeholder: "Enter your email" %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-md-2 control-label">
            <%= f.label :password %>
          </div>
          <div class="col-md-8">
            <%= f.password_field :password, class: "form-control", placeholder: "Choose your password" %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-md-2 control-label">
            <%= f.label :password_confirmation, "Confirm password" %>
          </div>
          <div class="col-md-8">
            <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirm your password" %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-md-offset-2 col-md-10">
            <%= f.submit(@chef.new_record? ? "Create my account" : "Update account information", class: "btn btn-primary btn-lg") %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="col-md-offset-2">
    <p><small><%= link_to "Cancel and return to view all recipes", recipes_path %></small></p>
  </div>

app/views/chefs/edit.html.erb
<div class="container">
  <%= render 'shared/page_title', title: "Edit your account information" %>
  <%= render 'form' %>
</div>

app/views/chefs/new.html.erb
<div class="container">
  <%= render 'shared/page_title', title: "Sign up for the application" %>
  <%= render 'form' %>
</div>

app/views/chefs/show.html.erb
<div class="container">
  <%= render 'shared/page_title', title: "#{@chef.chefname}'s page" %>
  <div class="row">
    <div class="col-md-2 col-md-offset-2">
      <%= gravatar_for @chef, size: 100 %>
    </div>
    <div class="col-md-6">
      <% @chef.recipes.each do |recipe| %>
        <h3><%= link_to recipe.name, recipe_path(recipe) %></h3>
        <p><%= truncate(recipe.description, length: 50) %></p>
        <div class="created-by">
          <p>Created <%= time_ago_in_words(recipe.updated_at) %></p>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% if flash.any? %>
  <div class="flash-msg">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %> alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= value %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "ChefBook", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Recipes<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "View all recipes", recipes_path %></li>
            <li><%= link_to "Create new recipe", new_recipe_path %></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChefBook</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <footer>
      <hr>
      <p>Created by Regina.H, following Mashrur Hossain's Professional Ruby on Rails Course</p>
      <p>&copy; 2017 ReginaStudio</p>
    </footer>
  </body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron" id="bg-home-page">
  <div class="container" id="tagline">
    <h1>From my kitchen to yours</h1>
    <p>A space where we share recipes with the world.</p>
    <p><%= link_to "Sign up", signup_path, class: "btn btn-danger btn-lg" %> <%= link_to "View all recipes", recipes_path, class: "btn btn-primary btn-lg" %></p>
  </div>
</div>

app/views/recipes/_form.html.erb
<div class="container">
  <%= render 'shared/error-msg', obj: @recipe %>

  <div class="row">
    <div class="col-md-12">
      <%= form_for(@recipe, :html => {class: "form-horizontal", role: "form"}) do |f| %>
        <div class="form-group">
          <div class="col-md-2 control-label">
            <%= f.label :name %>
          </div>
          <div class="col-md-8">
            <%= f.text_field :name, class: "form-control", placeholder: "Recipe name", autofocus: true %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-md-2 control-label">
            <%= f.label :description %>
          </div>
          <div class="col-md-8">
            <%= f.text_area :description, class: "form-control", rows: 20, placeholder: "Describe the steps here" %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-md-offset-2 col-md-8">
            <%= f.submit(@recipe.new_record? ? "Create" : "Edit", class: "btn btn-default") %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="col-md-offset-2">
    <p><small><%= link_to "Cancel and return to view all recipes", recipes_path %></small></p>
  </div>
</div>

app/views/recipes/edit.html.erb
<div class="container">
  <%= render 'shared/page_title', title: "Edit your recipe" %>
  <%= render 'form' %>

</div>

app/views/recipes/index.html.erb
<div class="container">
  <%= render 'shared/page_title', title: "All recipes" %>

    <div class="row">
      <% @recipes.each do |recipe| %>
        <div class="col-md-4">
          <div class="panel panel-default">
            <div class="panel-body">
              <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
              <p><%= truncate(recipe.description, length: 40) %></p>
              <div class="created-by">
                <p>Shared by <%= recipe.chef.chefname %> <%= time_ago_in_words(recipe.updated_at) %> ago</p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>

</div>

app/views/recipes/new.html.erb
<div class="container">
  <%= render 'shared/page_title', title: "Create a new recipe" %>
  <%= render 'form' %>

</div>

app/views/recipes/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <%= render 'shared/page_title', title: @recipe.name %>

      <h3>How to do it</h3>
      <p><%= simple_format(@recipe.description) %></p>

      <div class="recipe-actions">
        <%= link_to "Edit this recipe", edit_recipe_path(@recipe), class: "btn btn-xs btn-warning" %>
        <%= link_to "Delete this recipe", recipe_path(@recipe), method: :delete, data: { confirm: "Are you sure you want to delete this recipe?" }, class: "btn btn-xs btn-danger" %>
        <%= link_to "Return to All recipes", recipes_path, class: "btn btn-xs btn-primary" %>
      </div>

      <div class="created-by">
        <p><%= link_to gravatar_for(@recipe.chef, size: 50), recipes_path %></p>
        <p>Shared by <%= @recipe.chef.chefname %> <%=time_ago_in_words(@recipe.updated_at) %> ago</p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_error-msg.html.erb
<% if obj.errors.any? %>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-danger">
      <div class="panel-heading">
        <h2 class="panel-title"><%= pluralize(obj.errors.count, "error") %> prohibited this <%= obj.class %> from being saved:</h2>
      </div>
      <div class="panel-body">
        <ul>
          <% obj.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/shared/_page_title.html.erb
<div class="page-title-div">
  <h1><%= title.capitalize %></h1>
</div>